=== VincentdArras/noho_passerelle/FichiersExemples/ProshopVente.dtd
<!--
	*****************************************************************************************************	
	les balises :
	===============
		?  sont les rubriques facultatives du fichier des ventes de Proshop. 
		Si elles sont renseignées, leurs valeurs seront enregistrées.

		Les autres balises représentent les données obligatoires
		
	les attributs :
	=================
		#IMPLIED  sont des données facultatives.Ce sont des rubriques de fichiers liés aux ventes
		Elles existent d'une facon obligatoires ou non dans Proshop, mais ne seront pas enregistrées. 
		Elles peuvent servir pour info, requetes, controles etc. 

		#REQUIRED sont des données obligatoires pour l'enregistrement des ventes dans Proshop.
		Elles sont communes à tous les élements fils
	
	Les entités et CDATA :
	=======================
		Les sections CDATA 	ne sont pas reconnues par WINDEV par conséquent  
			 Ne pas écrire : 	<nom><![CDATA[DUPOND & CIE]]></nom>
					Ecrire :	<nom>DUPOND &amp; CIE</nom>
		
		Entités XML à respecter :		
			&lt; 	< 	inférieur à
			&gt; 	> 	supérieur à
			&amp; 	& 	et commercial
			&apos; 	' 	apostrophe
			&quot; 	" 	double quote
		
    Type de données
    ====================
    exemple    magasin entier <= 3  = entier sur 3 chiffres maximum
	*****************************************************************************************************
	-->

<!ELEMENT proshop (ventes+)>

<!ATTLIST proshop
	datesysteme 		CDATA   #REQUIRED > 	
	<!-- date et heure de création du document 
      datetime AAAA-MM-JJtHH-MM-SS -->
	
<!ELEMENT ventes (ticket+) >
<!ATTLIST ventes 
	date 		CDATA #REQUIRED 				 	
	magasin CDATA	#REQUIRED >
	<!-- 	date AAAA-MM-JJ
			  magasin entier <= 3 -->
	
<!ELEMENT ticket (client?, produits, reglements) >
<!ATTLIST ticket
	numero 	 CDATA 	#REQUIRED	
	heure 	 CDATA 	#REQUIRED >
	<!--  numero: chaine
        heure: HH:MM -->

<!ELEMENT client  (code?,nofidelite?,civilite?,nom,prenom?,adresse1?,adresse2?,codepostal?,ville?,telephone?, email?,commentaire?) >
<!ELEMENT code 			 	(#PCDATA)>		<!-- 2 < chaine < 14 -->
<!ELEMENT nofidelite	 	(#PCDATA)>		<!-- gencod numérique 12 | 13-->
<!ELEMENT civilite 			(#PCDATA)>		<!-- chaine < 7 -->
<!ELEMENT nom 				(#PCDATA)>		<!-- 2 < chaine < 36 -->
<!ELEMENT prenom 			(#PCDATA)>		<!-- chaine < 26 -->
<!ELEMENT adresse1 			(#PCDATA)>		<!-- chaine < 36 -->
<!ELEMENT adresse2 			(#PCDATA)>		<!-- chaine < 36 -->
<!ELEMENT codepostal		(#PCDATA)>		<!-- chaine < 9 -->
<!ELEMENT ville				(#PCDATA)>		<!-- chaine < 31 -->
<!ELEMENT telephone			(#PCDATA)>		<!-- chaine < 21 -->
<!ELEMENT email				(#PCDATA)>		<!-- chaine < 51 -->
<!ELEMENT commentaire 		(#PCDATA)>		<!-- chaine < 31 -->

	
<!ELEMENT produits (article+)>
		
<!ELEMENT article (type?, gencod,taille,prht?,tva?,pvttc,quantite?, remise?,coderemise?, commentaire?)>
<!ATTLIST article 
	libelle 			CDATA 	#IMPLIED
  couleur 		CDATA 	#IMPLIED
	fournisseur			CDATA 	#IMPLIED
	gfsf	 			CDATA 	#IMPLIED
	ligneproduit		CDATA 	#IMPLIED
	collection 			CDATA 	#IMPLIED >
	<!--Aucune contrainte -->

<!ELEMENT type			(#PCDATA)>		<!-- chaine "V" |H | BA -->
<!ELEMENT gencod		(#PCDATA)>		<!-- gencod 12 | 13 -->
<!ELEMENT taille		(#PCDATA)>		<!-- 0 < chaine < 5 -->
<!ELEMENT prht			(#PCDATA)>		<!-- reel -->
<!ELEMENT tva			(#PCDATA)>		<!-- reel -->
<!ELEMENT pvttc			(#PCDATA)>		<!-- reel -->
<!ELEMENT quantite		(#PCDATA)>		<!-- entier -->
<!ELEMENT remise		(#PCDATA)>		<!-- reel -->
<!ELEMENT coderemise 	(#PCDATA)>		<!-- chaine < 5 -->


<!ELEMENT reglements (mode+)>			
<!ELEMENT mode	(code,montant)>
<!ATTLIST mode
	libelle CDATA #IMPLIED > <!--Aucune contrainte -->

<!--ELEMENT 	code	(#PCDATA)>	voir plus haut		 1 < chaine < 6 -->
<!ELEMENT montant	(#PCDATA)>		<!-- reel -->

=== VincentdArras/noho_passerelle/FichiersExemples/Web200806181512.xml
<?xml version='1.0'  encoding="iso-8859-1"?>
<!DOCTYPE proshop SYSTEM "ProshopVente.dtd">


<proshop datesysteme="2008-06-18T15:12:30">
	<ventes date="2008-06-06" magasin="003">
		<ticket numero="12564" heure="10:05:33"> 			
			<client>
				<code>152365425</code>
				<nom>AUFRAISE</nom>
				<prenom>charlotte</prenom>
				<adresse1>15 impasse du bout du monde</adresse1>
				<codepostal>33000</codepostal>
				<ville>BORDEAUX</ville>
			</client>
			<produits>
				<article libelle="pantalon toile" collection="E08">
					<gencod>001222152124</gencod>
					<taille>=xl</taille>
					<pvttc>45.30</pvttc>
					<quantite>2</quantite>
				</article>
				<article>
					<gencod>001258258122</gencod>
					<taille>34</taille>
					<pvttc>20</pvttc>
					<remise>5</remise>
					<coderemise>ami</coderemise>
				</article>
			</produits>
			<reglements>
				<mode>
					<code>cb</code>
					<montant>65.30</montant>
				</mode>
			</reglements>
		</ticket>
		<ticket numero="12566" heure="10:12:25">
			<client>
				<code>152365425</code>
				<nom>DUPOND &amp;CIE</nom>
				<ville>Avignon</ville>
				<email>dupond@libre.fr</email>
			</client>
			<produits>
				<article>
					<gencod>001222169603</gencod>
					<taille>xxl</taille>
					<pvttc>70</pvttc>
				</article>
			</produits>			
			<reglements>
				<mode>
					<code>cb</code>
					<montant>70</montant>
				</mode>
			</reglements>
		</ticket>
	</ventes>
	<ventes date="2008-06-06" magasin="004">
		<ticket numero="00464" heure="09:05:11"> 			
			<client>
				<code>1525</code>
				<nom>MARTIN</nom>
			</client>
			<produits>
				<article>
					<gencod>001222150006</gencod>
					<taille>=38</taille>
					<pvttc>82.30</pvttc>
					<remise>2.30</remise>
					<coderemise>*S</coderemise>
				</article>
			</produits>
			<reglements>
				<mode>
					<code>CB</code>
					<montant>80.00</montant>
				</mode>
			</reglements>
		</ticket>
	</ventes>
</proshop>

=== VincentdArras/noho_passerelle/Ancienne passerelle/CommandesClientNoho.20210307190202.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE proshop SYSTEM "ProshopVente.dtd">
<proshop datesysteme="2021-03-07T19:02:02">
 <ventes date="2021-03-07" magasin="008">
  <ticket numero="867" heure="18:32:15">
   <client>
    <code>2301</code>
    <nom>ALSINA</nom>
    <prenom>Magali</prenom>
    <adresse1>2 rue des Vergers</adresse1>
    <codepostal>66300</codepostal>
    <ville>Thuir</ville>
   </client>
   <article>
    <type>R</type>
    <gencod>FDP</gencod>
    <taille/>
    <pvttc></pvttc>
    <remise/>
    <coderemise/>
   </article>
   <reglements>
    <mode>
     <code>cb</code>
     <montant>0.000000</montant>
    </mode>
   </reglements>
  </ticket>
 </ventes>
</proshop>

=== VincentdArras/noho_passerelle/FichiersExemples/WebExemple.xml
<?xml version='1.0'  encoding="iso-8859-1"?>
 <!DOCTYPE proshop SYSTEM "ProshopVente.dtd">

<proshop datesysteme="2008-06-18T15:12:30">
	<ventes date="2008-06-07" magasin="003">
		<ticket numero="12564" heure="10:05:33"> 			
			<client>
				<code>152365425</code>
				<nom>AUFRAISE</nom>
				<prenom>charlotte</prenom>
				<adresse1>15 impasse du bout du monde</adresse1>
				<codepostal>33000</codepostal>
				<ville>BORDEAUX</ville>
			</client>
			<produits>
				<article libelle="pantalon toile" collection="E08">
					<type>V</type>
					<gencod>9001058674015</gencod>
					<taille>=TU</taille>
					<pvttc>4.50</pvttc>
					<quantite>2</quantite>
				</article>
				<article>
					<type>R</type>
					<gencod>FDP</gencod>
					<taille></taille>
					<pvttc>8.50</pvttc>
					<remise></remise>
					<coderemise></coderemise>
				</article>
			</produits>
			<reglements>
				<mode>
					<code>cb</code>
					<montant>11.0</montant>
				</mode>
			</reglements>
		</ticket>
	</ventes>
</proshop>

=== VincentdArras/noho_passerelle/Ancienne passerelle/CommandesClientNoho.20210226230202.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE proshop SYSTEM "ProshopVente.dtd">
<proshop datesysteme="2021-02-26T23:02:02">
 <ventes date="2021-02-26" magasin="008">
  <ticket numero="853" heure="22:59:54">
   <client>
    <code>2117</code>
    <nom>LOPES</nom>
    <prenom>Laetitia</prenom>
    <adresse1>15 Chemin Du Mas Dels Chots</adresse1>
    <codepostal>66330</codepostal>
    <ville>Cabestany</ville>
   </client>
   <article libelle="Pantalon Simili Cuir Noir PA - Tailles : M" collection="PA">
    <type>V</type>
    <gencod>9005014872033</gencod>
    <taille>M</taille>
    <pvttc>11.996000</pvttc>
    <quantite>1</quantite>
   </article>
   <article libelle="Pantalon Simili Cuir Noir PA - Tailles : S" collection="PA">
    <type>V</type>
    <gencod>9005014872026</gencod>
    <taille>S</taille>
    <pvttc>11.996000</pvttc>
    <quantite>1</quantite>
   </article>
   <article libelle="PANTALON SIMILI NOIR MARIE - Tailles : 40" collection="MARIE">
    <type>V</type>
    <gencod>9005017708056</gencod>
    <taille>40</taille>
    <pvttc>15.996000</pvttc>
    <quantite>1</quantite>
   </article>
   <reglements>
    <mode>
     <code>cb</code>
     <montant>40.000000</montant>
    </mode>
   </reglements>
  </ticket>
 </ventes>
</proshop>
